language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t peterfarouk/travis-test:latest .
  - docker login -u "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
  - docker push peterfarouk/travis-test:latest

after_success:
 - echo "done"
  
